client:
    output: human
    retries: 1
    timeout: 30s
dbms:
    image: postgres:17
defaultProfile: local
engine:
    storePath: C:\Users\Zlygo\AppData\Local\sqlrs\store\btrfs.vhdx
    wsl:
        distro: Ubuntu
        mode: auto
        mount:
            device: /dev/sdg2
            deviceUUID: e5ce4e96-2dcc-4d16-8a60-4d580af9d46b
            fstype: btrfs
            unit: home-sinclair-.local-state-sqlrs-store.mount
        stateDir: /home/sinclair/.local/state/sqlrs/store
orchestrator:
    daemonPath: ../../dist/bin/sqlrs-engine-linux-amd64
    idleTimeout: 120s
    runDir: ${StateDir}/run
    startupTimeout: 20s
profiles:
    local:
        auth:
            mode: fileToken
        autostart: true
        endpoint: auto
        mode: local
