client:
    output: human
    retries: 1
    timeout: 30s
dbms:
    image: postgres:17
defaultProfile: local
engine:
    storePath: C:\Users\Zlygo\AppData\Local\sqlrs\store\btrfs.vhdx
    wsl:
        distro: Ubuntu
        mode: auto
        mount:
            device: /dev/sdh2
            fstype: btrfs
        stateDir: /home/sinclair/.local/state/sqlrs/store
orchestrator:
    daemonPath: ../../dist/bin/sqlrs-engine-linux-amd64
    idleTimeout: 120s
    runDir: ${StateDir}/run
    startupTimeout: 5s
profiles:
    local:
        auth:
            mode: fileToken
        autostart: true
        endpoint: auto
        mode: local
